/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person.gltf 
*/

import React from 'react'
import { Environment, useGLTF } from '@react-three/drei'
import { useFrame, Canvas } from '@react-three/fiber';

export default function Model(props) {
  const { nodes, materials } = useGLTF('./src/assets/person.gltf')
  return (
    <>
     <Canvas camera={{ position: [1, 0, 1] }}>
        <group {...props} dispose={null} position={[0,-1,0]}>
          <mesh geometry={nodes['Man_03_-_Renderpeople'].geometry} material={materials['Ramon - Renderpeople']}/>
        </group>
        <Environment preset="sunset" />
      </Canvas>
    </>
   
  )
}

useGLTF.preload('./src/assets/person.gltf')
