/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 person.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./public/person.gltf')
  return (
    <>
     <group {...props} dispose={null}>
      <mesh geometry={nodes['Man_03_-_Renderpeople'].geometry} material={materials['Ramon - Renderpeople']}/>
    </group>
    </>
   
  )
}

useGLTF.preload('./public/person.gltf')
